# Generated by Django 5.2.12 on 2026-03-13 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
